import {
  AppWindow,
  BadgeDollarSign,
  Bot,
  Box,
  Brain,
  BriefcaseBusiness,
  Calendar,
  ChartNoAxesColumn,
  Cloud,
  CodeXml,
  Cpu,
  Database,
  Goal,
  Gauge,
  GitMerge,
  Images,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Mail,
  MailCheck,
  Map,
  MapPinned,
  Megaphone,
  MessageCircleMore,
  MessageSquareQuote,
  Monitor,
  MonitorSmartphone,
  Newspaper,
  Palette,
  Plug,
  RefreshCw,
  Rocket,
  Search,
  SearchCheck,
  ServerCog,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  UtensilsCrossed,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  "app-window": AppWindow,
  "badge-dollar-sign": BadgeDollarSign,
  bot: Bot,
  box: Box,
  brain: Brain,
  "briefcase-business": BriefcaseBusiness,
  calendar: Calendar,
  "chart-no-axes-column": ChartNoAxesColumn,
  cloud: Cloud,
  "code-xml": CodeXml,
  cpu: Cpu,
  database: Database,
  goal: Goal,
  gauge: Gauge,
  "git-merge": GitMerge,
  images: Images,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  lightbulb: Lightbulb,
  mail: Mail,
  "mail-check": MailCheck,
  map: Map,
  "map-pinned": MapPinned,
  megaphone: Megaphone,
  "message-circle-more": MessageCircleMore,
  "message-square-quote": MessageSquareQuote,
  monitor: Monitor,
  "monitor-smartphone": MonitorSmartphone,
  newspaper: Newspaper,
  palette: Palette,
  plug: Plug,
  "refresh-cw": RefreshCw,
  rocket: Rocket,
  search: Search,
  "search-check": SearchCheck,
  "server-cog": ServerCog,
  "share-2": Share2,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  "utensils-crossed": UtensilsCrossed,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
};

export function getIcon(icon: string) {
  return iconMap[icon] ?? Palette;
}
